[project]
name = "BIDSlab"
dynamic = ["version"]
description = "A Python package for handling BIDS datasets."
authors = [
    { name = "Lukas Behammer", email = "lukas.behammer@uni-a.de" },
]
readme = "README.md"
requires-python = ">=3.11"
keywords = [
    "BIDS",
    "neuroimaging",
    "data management",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Private :: Do Not Upload", # !: Remove before publishing
]
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
dependencies = [
    "uritools",
    "pandas",
]

[project.optional-dependencies]
datalad = [
    "datalad",
]
tests = [
    "pytest",
    "pytest-cov",
    "pytest-xdist",
    "pytest-sugar",
    "pytest-random-order",
    "pytest-doctestplus",
    "syrupy",
    "mimesis",
]
lint = [
    "ruff",
]
docs = [
    "sphinx",
    "furo",
    "sphinxcontrib-email",
    "sphinx_copybutton",
    "sphinx-last-updated-by-git",
]
cd = [
    "python-semantic-release",
    "cibuildwheel",
]
build = [
    "build",
]
dev = [
    "mypy",
    "tox",
    "twine",
    "pre-commit",
    "BIDSlab[tests, lint, docs, cd, build]",
]

[project.urls]
#Repository
#Homepage
#Documentation
#Tracker
#Download

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

######################################################################
# Setuptools
[tool.setuptools.dynamic]
version = {attr = "bidslab.__version__"}

######################################################################
# Ruff
[tool.ruff]
extend-exclude = [
    "docs",
]
target-version = "py312"

[tool.ruff.lint]
preview = true
select = [
    "A",
    "ARG",
    "B",
    "C4",
    "C90",
    "CPY",
    "D",
    "E",
    "F",
    "I",
    "ICN",
    "N",
    #    "NPY",
    #    "PD",
    "PT",
    "PTH",
    "RET",
    "W",
]
ignore = [
    "B028",
    "D100", # TODO: Remove
    "D101", # TODO: Remove
    "D102", # TODO: Remove
    "D103", # TODO: Remove
    "D105", # TODO: Remove
    "D104",
    "D206",
    "D300",
    "E111",
    "E114",
    "E117",
    "W191",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ARG002", ]
"tools/generate_requirements.py" = ["CPY001", ] # TODO: Remove

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
known-first-party = ["src/BIDSlab"]

######################################################################
# MyPy
[tool.mypy]
exclude = [
    "tests",
    "data",
    "docs",
    "build",
    "dist",
    "tools",
    "templates",
    "branding",
    # TODO: Remove
    "src/temp",
    "src/bidslab/common/stim.py",
    "src/bidslab/common/physio.py",
    "src/bidslab/extensions",
]
files = "src/bidslab"
strict = false
pretty = true
disable_error_code = ["import-not-found"]

[[tool.mypy.overrides]]
module = [
    "uritools",
]
ignore_missing_imports = true

######################################################################
# PyTest
[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "--cov --cov-append --cov-report=term-missing --cov-report=xml --import-mode=importlib --random-order -n auto"
filterwarnings = [
    "error",
]

######################################################################
# Semantic Release
[tool.semantic_release]
commit_parser = "conventional"
logging_use_named_masks = true
allow_zero_version = true
major_on_zero = false
tag_format = "v{version}"
version_variables = ["./src/BIDSlab/__init__.py:__version__"]
commit_message = "chore(release): {version} (Automatically generated by python-semantic-release)"
build_command = "python -m build --sdist --wheel ."

[tool.semantic_release.changelog]
exclude_commit_patterns = [
    "\\[pre-commit\\.ci\\].*",
    "chore(?:\\([^)]*?\\))?: .+",
    "ci(?:\\([^)]*?\\))?: .+",
    "refactor(?:\\([^)]*?\\))?: .+",
    "style(?:\\([^)]*?\\))?: .+",
    "test(?:\\([^)]*?\\))?: .+",
    "build\\((?!deps\\): .+)",
    "book(?:\\([^)]*?\\))?: .+",
    "Merged? .*",
    "Create.*",
]

[tool.semantic_release.commit_parser_options]
allowed_types = [
    "build", "chore", "ci", "docs", "feat", "fix",
    "perf", "style", "refactor", "test",
]
minor_types = ["feat"]
patch_types = ["fix", "perf"]
