#!/usr/bin/env python
"""Generate reStructuredText TODO directives from a TODO file."""

#  Copyright (c) 2026 by Lukas Behammer
#  University of Augsburg
#  Department of Computer Science
#  Chair of Informatics for Medical Technology
#
#  SPDX-License-Identifier: BSD-3-Clause

from pathlib import Path

src = Path("TODO")
dst = Path("docs/source/generated/todos.rst")

if not src.exists():
    raise SystemExit("TODO file not found: TODO")

lines = src.read_text(encoding="utf-8").splitlines()
out = []
out.append(".. THIS FILE IS AUTO-GENERATED FROM THE TODO FILE")
out.append("   USING tools/generate_todos.py")
out.append("   DO NOT EDIT THIS FILE DIRECTLY!")
out.append("")
for ln in lines:
    ln = ln.replace("_", "\\_")
    if ln.startswith("TODO: "):
        content = ln[len("TODO: ") :].strip()
        out.append(f".. todo:: {content}")
        out.append("")  # blank line after directive
    else:
        out.append(ln)

dst.parent.mkdir(parents=True, exist_ok=True)
# TODO: make more robust, add a newline at end if not present
dst.write_text("\n".join(out), encoding="utf-8")
print(f"Wrote {dst}")
